Repository hold17/drone, pull requests merged in 2018-06, with the labels that each got.

#17 Feature/search for qr
  autonomous-drone/src/main/java/dk/localghost/hold17/autonomous_drone/controller/DroneController.java
  autonomous-drone/src/main/java/dk/localghost/hold17/autonomous_drone/controller/KeyboardCommandManager.java
  autonomous-drone/src/main/java/dk/localghost/hold17/autonomous_drone/controller/QRScannerController.java
Labels: new-feature

#18 Feature/direction dynamics
  autonomous-drone/src/main/java/dk/localghost/hold17/autonomous_drone/opencv_processing/Direction.java
Labels: enhancement

#19 feature/circle-align
  autonomous-drone/src/main/java/dk/localghost/hold17/autonomous_drone/controller/DroneController.java
  autonomous-drone/src/main/java/dk/localghost/hold17/autonomous_drone/controller/KeyboardCommandManager.java
  autonomous-drone/src/main/java/dk/localghost/hold17/autonomous_drone/controller/QRCodeScanner.java
  autonomous-drone/src/main/java/dk/localghost/hold17/autonomous_drone/gui/AutonomousGUI.java
  autonomous-drone/src/main/java/dk/localghost/hold17/autonomous_drone/gui/GUIController.java
  autonomous-drone/src/main/java/dk/localghost/hold17/autonomous_drone/opencv_processing/Benchmark.java
  autonomous-drone/src/main/java/dk/localghost/hold17/autonomous_drone/opencv_processing/CircleFilter.java
  autonomous-drone/src/main/java/dk/localghost/hold17/autonomous_drone/opencv_processing/RectangleFilter.java
  autonomous-drone/src/main/java/dk/localghost/hold17/autonomous_drone/opencv_processing/util/Direction.java
  yadrone-core/src/main/java/dk/localghost/hold17/base/command/CommandManager.java
  yadrone-core/src/main/java/dk/localghost/hold17/base/utils/ConsoleColors.java
Labels: needs testing
